function eprimeData = import_ePrime_data(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
% Auto-generated by MATLAB on 13-nov-2023 19:39:17

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 22);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Subject", "CodiceAlfaNumerico", "durstim", "Group", "restingDurationDefault", "SessionStartDateTimeUtc", "SessionTime", "Trial", "DotSide", "FileName", "ID", "Misogynous", "Objectification", "pictureTrialOnsetTime", "questionTrialRESP", "questionTrialRT", "restingDuration", "restingTrialOnsetTime", "SelectedMEME", "Shaming", "Stereotype", "Violence"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "datetime", "duration", "double", "categorical", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "FileName", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CodiceAlfaNumerico", "DotSide", "FileName"], "EmptyFieldRule", "auto");

% Import the data
eprimeData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    eprimeData = [eprimeData; tb]; %#ok<AGROW>
end

end