clc
clear all
%%
source_root = 'C:\Users\lisac\Desktop\SELECTED_MEME\';
root = 'C:\Users\lisac\Desktop\Groups\group';

%% 
clc
[selectedMEME_tab, randomgroups_tab] = importData();

randomgroups = table2array(randomgroups_tab);
selectedMEME = table2array(selectedMEME_tab);
clear selectedMEME_tab randomgroups_tab

%%
clc
for i = 1 : size(randomgroups,2)
    destination_root = strcat(root, string(i));
    mkdir(destination_root);

    for j = 1 : size(randomgroups,1)
        id = randomgroups(j,i);
        meme = findMEME(selectedMEME, id);
        group = string(num2str(i, '%02.f'));
        number = string(num2str(j, '%02.f'));
        destination = destination_root + '\' + ...
                        group + "-" + number + "_" + meme
        source = source_root + meme;
        copyfile (source, destination);
    end
end

%%

function  meme = findMEME (selectedMEME, id)
    for i = 1 : size(selectedMEME,1)
        if(double(selectedMEME(i,1)) == id)
            meme = selectedMEME(i,2);
            return
        end
    end
end


function [selectedMEME, randomgroups] = importData ()
    %% Import data from spreadsheet
    % Script for importing data from the following spreadsheet:
    %
    %    Workbook: C:\Users\lisac\Desktop\selected_MEME.xlsx
    %    Worksheet: Sheet1
    %
    % Auto-generated by MATLAB on 04-set-2023 16:47:30
    
    %% Set up the Import Options and import the data
    opts = spreadsheetImportOptions("NumVariables", 2);
    
    % Specify sheet and range
    opts.Sheet = "Sheet1";
    opts.DataRange = "A2:B97";
    
    % Specify column names and types
    opts.VariableNames = ["ID", "FileName"];
    opts.VariableTypes = ["double", "string"];
    
    % Specify variable properties
    opts = setvaropts(opts, "FileName", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "FileName", "EmptyFieldRule", "auto");
    
    % Import the data
    selectedMEME = readtable("C:\Users\lisac\Desktop\selected_MEME.xlsx", opts, "UseExcel", false);
    
    %% Set up the Import Options and import the data
    opts = spreadsheetImportOptions("NumVariables", 40);
    
    % Specify sheet and range
    opts.Sheet = "Sheet1";
    opts.DataRange = "A2:AN25";
    
    % Specify column names and types
    opts.VariableNames = ["group1", "group2", "group3", "group4", "group5", "group6", "group7", "group8", "group9", "group10", "group11", "group12", "group13", "group14", "group15", "group16", "group17", "group18", "group19", "group20", "group21", "group22", "group23", "group24", "group25", "group26", "group27", "group28", "group29", "group30", "group31", "group32", "group33", "group34", "group35", "group36", "group37", "group38", "group39", "group40"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];
    
    % Import the data
    randomgroups = readtable("C:\Users\lisac\Desktop\random_groups.xlsx", opts, "UseExcel", false);
    
    
    %% Clear temporary variables
    clear opts
end

